# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# trigger:
#  none

# pr: none

parameters:
  - name: vmImage
    type: string
    default: ubuntu-latest
  
jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: npm install
    displayName: NPM installation
  # - script: npm test
  - script: echo Hello, world!
    displayName: 'Run a one-line script'


# - script: echo '$(Build.BuildNumber)'
#   displayName: 'Displays Build Number'
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
