# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 none

# Repo: Contoso/LinuxProduct
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: templates
      type: github
      name: vnssr25/pipelines-multistage
      endpoint: vnssr25
  pipelines:
    - pipeline: pipelineTrigger
      source: vnssr25.pipelines-multistage
      trigger:
       stages:
         - PreProd

stages:
- stage: Build
  displayName: NPM step
  jobs:
   - template: azure-pipelines.yml@templates 
     parameters:
      vmImage: 'windows-latest'
- stage: Test
  displayName: Test
  dependsOn: []
  jobs:
    - job : TestonWindows
      steps:
        - script: echo Testing on Windows!
    - job: TestonLinux
      steps:
        - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!
- stage: PreProd
  jobs:
   - deployment: preprod
     displayName: Deploy in Pre Prod
     pool:
      name: Hosted Windows 2019 with VS2019 
      vmImage: windows-latest 
     environment: preprod
     strategy:
      runOnce:
        deploy:
          steps:
            - script: echo preprod deployment
            - pwsh: |
                   Write-Host "Mulitline preprod Script1"
                   Write-Host "Mulitline preprod Script2"
